const ContactData = [
  {
    id: 1,
    heading: "Welcome",
    title: "Start Your Journey",
    titleComponent: null,
    tipTitle: "Getting Started",
    tipContent: "Follow the guide to set up your account quickly.",
    additionalInfo: "This will help you get up and running in no time.",
    buttonText: "Start Now",
    onClose: () => console.log("Welcome tip closed."),
    onUpdateInfo: (info) => console.log("Info updated:", info),
  },
  {
    id: 2,
    // heading: "Profile Setup",
    title: "Personalize Your Profile",
    titleComponent: null,
    tipTitle: "Complete Your Profile",
    tipContent: "Add your details to personalize your experience.",
    additionalInfo: "Ensure your information is accurate.",
    buttonText: "Update Profile",
    onClose: () => console.log("Profile setup tip closed."),
    onUpdateInfo: (info) => console.log("Profile info updated:", info),
  },
  {
    id: 3,
    heading: "Notifications",
    title: "Stay Informed",
    titleComponent: null,
    tipTitle: "Enable Notifications",
    tipContent: "Stay updated by enabling notifications.",
    additionalInfo: "You can change this anytime in settings.",
    buttonText: "Enable Now",
    onClose: () => console.log("Notifications tip closed."),
    onUpdateInfo: (info) => console.log("Notifications info updated:", info),
  },
  {
    id: 4,
    heading: "Security",
    title: "Protect Your Account",
    titleComponent: null,
    tipTitle: "Secure Your Account",
    tipContent: "Enable two-factor authentication for enhanced security.",
    additionalInfo: "This adds an extra layer of protection to your account.",
    buttonText: "Secure Now",
    onClose: () => console.log("Security tip closed."),
    onUpdateInfo: (info) => console.log("Security info updated:", info),
  },
  {
    id: 5,
    heading: "Feedback",
    title: "Share Your Thoughts",
    titleComponent: null,
    // tipTitle: "We Value Your Feedback",
    tipContent: "Let us know your thoughts to help us improve.",
    additionalInfo: "Your input makes a difference.",
    buttonText: "Give Feedback",
    onClose: () => console.log("Feedback tip closed."),
    onUpdateInfo: (info) => console.log("Feedback info updated:", info),
  },
];


export default ContactData;
